server:
  port: 8091
logging:
  level:
    org.novel.controller: debug

spring:
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tang?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl